### ISSUE TITLE
USER STORY: Post Details

### ISSUE THREAD

**Issue by Viacheslav1510** [Viacheslav1510/CI_PB_PP4#12]
As a **User** I can **open post details** so I  **can see detailed post information and leave a comment**

## **Acceptance Criteria**

**Given** I am on a blog page
**When** I click a post title or image
**Then** I can see post details and comments section

## **Tasks**

- [x] Links for post details in title and post image
- [x] Post details page
- [x] Edit/Delete buttons
- [x] Comments section
